services:
  - type: web
    name: gaia-hub
    runtime: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: GAIA_PORT
        value: "3000"
      - key: GAIA_ENABLE_CORS
        value: "true"
      - key: GAIA_CORS_ORIGIN
        value: "https://memory-card-game-xi-navy.vercel.app"
      - key: GAIA_HUB_URL
        value: "https://gaia-hub-render.onrender.com"
      - key: GAIA_DOMAIN_NAME
        value: "gaia-hub-render.onrender.com"
